baseURL: https://sazl.ca
languageCode: en-us
defaultContentLanguage: en
title: sazl
theme: cupper-hugo-theme
enableGitInfo: true

module:
  imports:
  - path: github.com/theNewDynamic/hugo-module-tnd-socials

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: sazl.ca
  homeMetaContent: Sami Zeinelabdin
  footer: sazl
  dateFormat: Jan 2, 2006
  codePenUser: sazl
  katex: true

  tnd_socials:
      services:
      - name: github
        handle: sazl
      - name: twitter
        handle: optimaltree
        url: https://www.twitter.com/optimaltree
        icon: twitter
      - name: instagram
        handle: optimaltree
        url: https://www.instagram.com/optimaltree

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: About
      url: /about/
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
